# Generated by Django 4.2.21 on 2025-06-11 21:15

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='visibility',
            field=models.ForeignKey(blank=True, help_text='When configured, will hide this step from users unless this check resolves to true or this step is the next incomplete step', null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.check'),
        ),
        migrations.AlterField(
            model_name='step',
            name='checks',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='steps', to='workflows.check'),
        ),
    ]
